### ISSUE TITLE
ImportError: cannot import name 'tensor' when using sparse partial tucker in Google Colab

### ISSUE THREAD

**Issue by mitarj** [tensorly/tensorly#100]
When I install tensorly in Colab with the following command:
`!pip install git+https://github.com/tensorly/tensorly.git`
And then import the sparse partial tucker like this:
`from tensorly.contrib.sparse.decomposition import partial_tucker`
I get the error:
`ImportError: cannot import name 'tensor'`

**Comment by asmeurer** [comment]
Should be fixed in https://github.com/tensorly/tensorly/pull/97

**Comment by mitarj** [comment]
Thank you. The `sparse-fix` branch from `Quansight` seems to work. The `main` branch from `tensorly` is still broken.

**Comment by asmeurer** [comment]
FYI the `sparse-master` branch from the Quansight fork has all the Quansight branches merged together (see the PRs list). You might consider using it if you are doing sparse work.

**Comment by JeanKossaifi** [comment]
Should be fixed now @mitarj?

**Comment by JeanKossaifi** [comment]
Should be fixed in master.
