### ISSUE TITLE
ValueError: On entry to SGESDD parameter number 10 had an illegal value

### ISSUE THREAD

**Issue by alam-shahul** [tensorly/tensorly#125]
I'm trying to use `tensorly.decomposition.tucker`, but I get this error from some Scipy LAPACK wrapper script:

```
ValueError: On entry to SGESDD parameter number 10 had an illegal value
```

Any idea what the problem might be? I am making sure to apply `nan_to_num` to my tensor before trying to decompose it.

**Comment by JeanKossaifi** [comment]
I am assuming you are using the NumPy backend?

Can you post your version of tensorly (`tensorly.__version__`) and a minimal piece of code to reproduce the error?

**Comment by alam-shahul** [comment]
Hmm, I think that error was due to a bug in my code that I just fixed. However, I get the following output when running the decomposition after fixing that bug:

```
/opt/notebooks/environments/allpurpose/lib/python3.6/site-packages/tensorly/backend/core.py:704: RuntimeWarning: invalid value encountered in sqrt
  S = np.sqrt(S)
/opt/notebooks/environments/allpurpose/lib/python3.6/site-packages/tensorly/backend/core.py:710: RuntimeWarning: invalid value encountered in sqrt
  S = np.sqrt(S)
reconsturction error=nan, variation=nan.
reconsturction error=nan, variation=nan.
reconsturction error=nan, variation=nan.
reconsturction error=nan, variation=nan.
reconsturction error=nan, variation=nan.
...
```

All these `nan` values are kind of worrisome, and when I examine the core tensor/factors that result from the decomposition, they are also filled with `nan values.

The essential line of code that's causing the problem is:
```
core, factors = tensorly.decomposition.tucker(tensor_chunk, ranks=[args.annotation_components, args.snp_components, args.phenotype_components], \
                                                  n_iter_max=args.max_iterations, random_state=args.random_seed, verbose=1)
```
where `tensor_chunk` has shape (2779, 10, 4568).

I noticed that a lot of the slices of my input tensor along the first way are completely zero-valued. Is this why I'm getting these bad values from the decomposition?

**Comment by alam-shahul** [comment]
Also, I've noticed if I set one of the values in the `ranks` list to be equal to the number of dimensions in some way of the input tensor (for example, if I set `args.snp_components = 10`, then  I get the following error stacktrace:

```
/home/dnanexus/allpurpose/lib/python3.6/site-packages/tensorly/backend/core.py:704: RuntimeWarning: invalid value encountered in sqrt
  S = np.sqrt(S)
/home/dnanexus/allpurpose/lib/python3.6/site-packages/tensorly/backend/core.py:710: RuntimeWarning: invalid value encountered in sqrt
  S = np.sqrt(S)
Traceback (most recent call last):
  File "/opt/calculate_outer_product.py", line 41, in <module>
    n_iter_max=args.max_iterations, random_state=args.random_seed, verbose=1)
  File "/home/dnanexus/allpurpose/lib/python3.6/site-packages/tensorly/decomposition/_tucker.py", line 149, in tucker
    svd=svd, tol=tol, random_state=random_state, verbose=verbose)
  File "/home/dnanexus/allpurpose/lib/python3.6/site-packages/tensorly/decomposition/_tucker.py", line 87, in partial_tucker
    eigenvecs, _, _ = svd_fun(unfold(core_approximation, mode), n_eigenvecs=rank[index])
  File "/home/dnanexus/allpurpose/lib/python3.6/site-packages/tensorly/backend/core.py", line 695, in partial_svd
    U, S, V = scipy.linalg.svd(matrix, full_matrices=full_matrices)
  File "/home/dnanexus/allpurpose/lib/python3.6/site-packages/scipy/linalg/decomp_svd.py", line 109, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/home/dnanexus/allpurpose/lib/python3.6/site-packages/scipy/_lib/_util.py", line 239, in _asarray_validated
    a = toarray(a)
  File "/home/dnanexus/allpurpose/lib/python3.6/site-packages/numpy/lib/function_base.py", line 496, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

Is this not supported by `tensorly.decomposition.tucker`?

**Comment by alam-shahul** [comment]
I just wanted to bump this/was wondering if I could get a response?

**Comment by JeanKossaifi** [comment]
Hi @alam-shahul,
Sorry I missed your previous messages. It seems you are trying to apply SVD to a singular matrix so some of the eigenvalues would be 0, and the square root would return NaN. I will try to fix this.

**Comment by alam-shahul** [comment]
Thanks for getting back to me! So I don't quite remember all the details of the algorithm(s) used for Tucker decomposition/HOSVD, but does it involve taking the SVD of slices of the tensor? And is the SVD ill-defined for singular matrices? If so, then what would be the fix for the case where slices of the tensor are all zeros?

**Comment by JeanKossaifi** [comment]
I just pushed a commit that should fix your issue. Let me know if it works
for you.

**Comment by alam-shahul** [comment]
I still have the same problem. The warning look like this now:
```
/home/dnanexus/allpurpose/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: divide by zero encountered in log
  return func(*args2)
/home/dnanexus/allpurpose/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in multiply
  return func(*args2)
/home/dnanexus/tensorly/tensorly/backend/core.py:704: RuntimeWarning: invalid value encountered in less_equal
  S = np.where(np.abs(S) <= np.finfo(S.dtype).eps, 0, np.sqrt(S))
/home/dnanexus/tensorly/tensorly/backend/core.py:705: RuntimeWarning: invalid value encountered in less_equal
  V = np.dot(matrix.T.conj(), U * np.where(np.abs(S) <= np.finfo(S.dtype).eps, 0, 1/S)[None, :])
/home/dnanexus/tensorly/tensorly/backend/numpy_backend.py:51: RuntimeWarning: overflow encountered in square
  return np.sqrt(np.sum(tensor**2, axis=axis))
/home/dnanexus/tensorly/tensorly/backend/core.py:710: RuntimeWarning: invalid value encountered in less_equal
  S = np.where(np.abs(S) <= np.finfo(S.dtype).eps, 0, np.sqrt(S))
/home/dnanexus/tensorly/tensorly/backend/core.py:711: RuntimeWarning: invalid value encountered in less_equal
  U = np.dot(matrix, V) *  np.where(np.abs(S) <= np.finfo(S.dtype).eps, 0, 1/S)[None, :]
```

**Comment by JeanKossaifi** [comment]
But does it raise an error? Is the result still None?

**Comment by alam-shahul** [comment]
No error, but I still have
```
...
reconsturction error=nan, variation=nan.
...
```

**Comment by JeanKossaifi** [comment]
Can you post a minimal snipped of code to reproduce your issue?

**Comment by alam-shahul** [comment]
```
import numpy as np
import tensorly.decomposition

tensor_chunk = np.zeros((36, 8, 20))

x = [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 1,  1,  1,  1,  1,  1,  1,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]

y = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

z = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5, 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4, 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

# Setting non-zero values
for coord in zip(x, y, z):
    tensor_chunk[coord] = 1

core, factors = tensorly.decomposition.tucker(tensor_chunk, ranks=[5, 2, 3], n_iter_max=100, random_state=0, verbose=1)

```

So I found this to be a reasonably small example that yields these `np.nan` values. However, it doesn't throw any overflow errors, unlike my original tensor.

**Comment by alam-shahul** [comment]
I thought that the reason for the `np.nan` values might be that the original tensor contains values that, when squared, will overflow past the maximum allowed `np.float64` value. So I tried clipping the input tensor so that it didn't exceed the square root of this value. However, after doing this, I got the following error stacktrace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dnanexus/tensorly/tensorly/decomposition/_tucker.py", line 149, in tucker
    svd=svd, tol=tol, random_state=random_state, verbose=verbose)
  File "/home/dnanexus/tensorly/tensorly/decomposition/_tucker.py", line 74, in partial_tucker
    eigenvecs, _, _ = svd_fun(unfold(tensor, mode), n_eigenvecs=rank[index])
  File "/home/dnanexus/tensorly/tensorly/backend/core.py", line 702, in partial_svd
    np.dot(matrix, matrix.T.conj()), k=n_eigenvecs, which='LM'
  File "/home/dnanexus/allpurpose/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1667, in eigsh
    params.iterate()
  File "/home/dnanexus/allpurpose/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 572, in iterate
    raise ArpackError(self.info, infodict=self.iterate_infodict)
scipy.sparse.linalg.eigen.arpack.arpack.ArpackError: ARPACK error 3: No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV. 
```

This is yet _another_ error, different from the rest and even more cryptic.

**Comment by JeanKossaifi** [comment]
Well in that case the Higher-Order SVD cannot work as your tensor is almost all zero. In particular, for any k != 1, `tensor_chunk[:, k, :]` is all zeros, i.e. all the slices of your tensor but one are all zeros so you can just discard them.

It seems to me what you want is sparse tensors here (see  `tensorly.contrib.sparse`).

**Comment by alam-shahul** [comment]
So converting my tensor to a `sparse.COO` array and then using the sparse methods in `tensorly.contrib.sparse` should work?

Also, I think the original error was because, when some of the elements in my input tensor were squared, they overflowed the `np.float64` datatype. I guess there's not really a solution for this, except for maybe clipping my values to a maximum value of `np.sqrt(np.finfo(np.float64).max)`; do you agree?

**Comment by JeanKossaifi** [comment]
Did the sparse backend solve your issue?

Generally, it is good practice to normalise the input (e.g. substracting the mean, and dividing by the standard deviation), which might avoid overflow in your case.
