### ISSUE TITLE
Robust PCA mask not working

### ISSUE THREAD

**Issue by ccrnn** [tensorly/tensorly#451]
#### Describe the bug
Robust PCA can't be masked.
Robust PCA without mask works fine.

#### Steps or Code to Reproduce

```
import tensorly as tl
import numpy as np
import numpy.ma as ma

#after making (arr) numpy 3d array:
marr = ma.masked_invalid(arr)
sarr = np.nan_to_num(arr, nan = 0.0)
B = tl.tensor(sarr)
from tensorly.decomposition import robust_pca
PCA = robust_pca(B, mask = marr)
```

I also tried with
```
marr = (np.ma.masked_array(arr, np.isnan(arr))))
```

#### Expected behavior
Robust PCA with mask

#### Actual result

```
ValueError: array must not contain infs or NaNs
```

#### Versions

Windows-10-10.0.22000-SP0
Python 3.10.6 | packaged by conda-forge | (main, Oct  7 2022, 20:14:50) [MSC v.1916 64 bit (AMD64)]
NumPy 1.23.4
SciPy 1.9.2
TensorLy 0.7.0

**Comment by JeanKossaifi** [comment]
Seems like one of the arrays you're using has NaN or inf -- I suspect your mask since you called nan_to_num on the actual array. Can you try to pass in explicitly an array of booleans (or 0/1), for the mask, instead of a masked array?

**Comment by ccrnn** [comment]
Thanks, that works now!
Is there some percentage or structure of nans beyond which this is unlikely to work well? I have a lot of missing data, much of which is missing at the beginning of a time series, as variables started being measured at different times.

**Comment by ccrnn** [comment]
Also, is there a way to see the error on the robust PCA?
For instance, here: https://github.com/dganguli/robust-pca
It prints the error after a number of iterations. That's helpful, because the error didn't reduce for the unfolded version of the same tensor I'm using in tensorly. So I'm wondering if the tensor version also would have failed.

**Comment by JeanKossaifi** [comment]
Hi @ccrnn -- I've added an option `return_errors` so you can get back the reconstruction error over the iterations in 5ddd5387721bbff3c47faaa31f1db3e85c371722

**Comment by ccrnn** [comment]
Thanks so much for this! :)

It needed "return_errors=False" under def robust_pca to run... I'm not sure how to change it in 5ddd538 though

**Comment by JeanKossaifi** [comment]
Thanks @ccrnn, it's fixed in main!

**Comment by ccrnn** [comment]
Hi - sadly it seems like the mask is still not working properly - I get the same result whether the mask is on or off, as well as if I switch the 1s and 0s of the mask. The errors from the code above all seem fine though.
```
B = A.pivot_table(index = ['TIME'], columns = ['Variable'], values = 'Value', sort=True)

marr = np.isnan(B)
marr = 1 - marr

C = B.fillna(0.0)
C = tl.tensor(C)
D = tl.tensor(marr)
PCA1, PCA2, error = robust_pca(C, mask = D, reg_E=0.04, learning_rate=1.2, n_iter_max=100, return_errors=True)
```

**Comment by JeanKossaifi** [comment]
Great, I'll close the issue then, feel free to re-open / create a new one if you encounter any other issue!
